name: meu_pet_diario
description: Um aplicativo Flutter para gerenciar informações sobre pets.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  supabase_flutter: ^2.9.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1  # <-- Adicione esta linha
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true